### ISSUE TITLE
클립보드에서 이미지 붙여넣기

### ISSUE THREAD

**Issue by Nesffer** [RyuaNerin/QIT#2]
클립보드에서 이미지 붙여넣기가 안됩니다.

제일 중요한 건데...........

**Comment by RyuaNerin** [comment]
(후비

**Comment by RyuaNerin** [comment]
이거 새로 만들고 있어서 어떻게 될지 잘 모르겠어요. 요새 에린에서의 삶을 사느냐고 코딩을 안하고 있어서

**Comment by Usagination** [comment]
새로 만들다 때려쳤다던건 어쨌어

**Comment by RyuaNerin** [comment]
Quicx 인가 그거랑 통합하려는데

**Comment by Usagination** [comment]
멋진 생각인데

**Comment by Usagination** [comment]
[fixed](https://github.com/RyuaNerin/QIT/commit/ce8e1282f81f8d77d28133a4f2554ca7529cb407)

**Comment by RyuaNerin** [comment]
훌륭한 핫산 굿
