### ISSUE TITLE
트윗이 않되요

### ISSUE THREAD

**Issue by Usagination** [RyuaNerin/QIT#4]
트윗이 않되요 외않되요 트윗이 않되요 외않되요 트윗이 않되요 외않되요 트윗이 않되요 외않되요 트윗이 않되요 외않되요 트윗이 않되요 외않되요 트윗이 않되요 외않되요 트윗이 않되요 외않되요 트윗이 않되요 외않되요 트윗이 않되요 외않되요 트윗이 않되요 외않되요 트윗이 않되요 외않되요 트윗이 않되요 외않되요 트윗이 않되요 외않되요 트윗이 않되요 외않되요 트윗이 않되요 외않되요 트윗이 않되요 외않되요 트윗이 않되요 외않되요 트윗이 않되요 외않되요 트윗이 않되요 외않되요 트윗이 않되요 외않되요

**Comment by RyuaNerin** [comment]
싹 갈아아엎었는데 PSD 라이브러리 손대느냐고 커밋 안하는중

**Comment by Usagination** [comment]
안됐는데 이거 쓰고 빌드하니까 다시 됨

**Comment by Usagination** [comment]
Release 빌드에선 안됨
