### ISSUE TITLE
이슈 게시판에 본 프로젝트와 무관한 글을 등록하는 것은 자제해주시기 바랍니다.

### ISSUE THREAD

**Issue by Usagination** [RyuaNerin/QIT#8]
이슈 게시판에 쓸데없는 글을 쓰지 말라는 제목의 이 글의 내용은 쓸데없는 글이지만 아직 글이 등록되지 않았기 때문에 작성하는 시점에는 아무 문제가 되지 않을 것 같다

**Comment by RyuaNerin** [comment]
심심했구나
